language: php
php:
  - '7.2'

before_script:
  - phpenv config-rm xdebug.ini || true
  - composer install --no-interaction
  - touch database/database.sqlite
  - npm install
  - npm run prod

script:
  - composer test
  - php artisan code:analyse --level=max

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
