language: php
php:
  - "7.2.18"

cache:
  directories:
    - node_modules

before_script:
  - composer install --no-interaction
  - touch database/database.sqlite
  - npm install
  - npm run prod

script:
  - composer test
  - php artisan code:analyse
  - npm test
  - npm run coveralls

after_success:
  - travis_retry php vendor/bin/php-coveralls -v
