<?php
return [
    'advancement' => [
        'KeysC0' => 1,
        'BombsC4' => 1,
        'DivingSuit' => 1,
        'Transceiver' => 1,
        'Glasses' => 1,
        'Ladder' => 1,
        'Hammer' => 1,
        'Candle' => 1,
        'JumpShoes' => 1,
        'GoonieE0' => 1,
        'GoonieE1' => 1,
        'GoonieE2' => 1,
        'GoonieE3' => 1,
        'GoonieE4' => 1,
        'GoonieE5' => 1,
        'Hint 1' => 1,
        'Hint 2' => 1,
        'Hint 3' => 1,
        'Hint 4' => 1,
        'Hint 5' => 1,
        'Hint 6' => 1,
        'Hint 7' => 1,
        'Hint 8' => 1,
        'Hint 9' => 1,
        'Hint 10' => 1,
    ],
    'junk' => [
        'Helmet' => 1,
        'Raincoat' => 1,
        'HyperShoes' => 1,
        'Vest' => 1,
        'KeysC1' => 1,
        'KeysC2' => 1,
        'KeysC3' => 1,
        'BombsC5' => 1,
        'BombsC6' => 1,
        'BombsC7' => 1,
        'FireboxC8' => 1,
        'FireboxC9' => 1,
        'FireboxCA' => 1,
        'FireboxCB' => 1,
        'Boomerang' => 1,
        'Slingshot' => 1,
        'DeviceF0' => 1,
        'DeviceF1' => 1,
        'DeviceF2' => 1,
        'DeviceF3' => 1,
        'DeviceF4' => 1,
        'DeviceF5' => 1,
    ],
];
